---

- hosts: ocp-master[0]
  tasks:
  - name: get ocp version
    yum: 
      list: atomic-openshift-node
    register: openshift_rpm

  - name: send telegram message
    telegram:
      token: "{{ token }}"
      chat_id: "{{ chat_id }}"
      msg: "{{ tower_workflow_job_name }} - version {{ openshift_rpm.results[0].version }} -  {{ job_status }}"
    delegate_to: localhost
